version: '2.1'
services:
  configserver:
    image: umaruchan23/cloud-config:0.0.1
    restart: always
    ports:
      - "8071:8071"
    environment:
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_PASSWORD: ${GIT_PASSWORD}
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: umaruchan23/service-discovery:0.0.1
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_started
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    networks:
      backend:
        aliases:
          - "servicediscovery"
  rest:
    image: umaruchan23/rest:0.0.1
    restart: always
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      CLIENT_KEY: ${CLIENT_KEY}
    depends_on:
      configserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend
  gateway:
    image: umaruchan23/gatewayserver:0.0.1
    restart: always
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
      - "8072:8072"
    networks:
      - backend
  keycloak:
      image: quay.io/keycloak/keycloak
      restart: always
      ports:
        - "8080:8080"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      command:
        - start-dev
        - --import-realm
      volumes:
        - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json
      networks:
        backend:
          aliases:
            - "keycloak"
  feign-rest:
    image: umaruchan23/feign-rest:0.0.1
    restart: always
    environment:
      CLIENT_KEY: ${CLIENT_KEY}
    ports:
      - "8087:8087"
    networks:
      - backend
networks:
  backend:
    driver: bridge