version: '2.1'
services:
  configserver:
    image: umaruchan23/cloud-config:0.0.1
    ports:
      - "8071:8071"
    environment:
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_PASSWORD: ${GIT_PASSWORD}
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: umaruchan23/service-discovery:0.0.1
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
  rest:
    image: umaruchan23/rest:0.0.1
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      configserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend
  gateway:
    image: umaruchan23/gatewayserver-0.0.1
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      configserver:
        condition: service_started
    ports:
      - "8072:8072"
    networks:
      - backend
networks:
  backend:
    driver: bridge