spring:
  application:
    name: service-discovery
server:
  port: 8070
eureka:
  instance:
    hostname: servicediscovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5