spring:
  application:
    name: feign-rest
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cloud-test
            client-secret: ${CLIENT_KEY}
            authorization-grant-type: client_credentials
            provider: keycloak
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/simple-realm
            token-uri: http://keycloak:8080/realms/simple-realm/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/simple-realm

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://servicediscovery:8070/eureka/

server:
  port: 8087
